
#index:
#    path: /
#    controller: App\Controller\DefaultController::index
laskePalkka:
   # path kertoo mistä osoitteesta controlle löytyy
   path: /esimerkki/esim1
   controller: App\Controller\EsimerkitController::laskePalkka
karkausvuosi:
   path: /esimerkki/esim2
   controller: App\Controller\EsimerkitController::tarkistaKarkausvuosi
laskePH:
   path: /esimerkki/esim3
   controller: App\Controller\EsimerkitController::laskePH
heitaNoppaa:
   #http://127.0.0.1:8000/esimerkki/esim4
   path: /esimerkki/esim4
   controller: App\Controller\EsimerkitController::heitaNoppaa
naytaJson:
   path: /esimerkki/esim5
   controller: App\Controller\EsimerkitController::naytaJson
lihapiirakka:
   path: /esimerkki/esim6
   controller: App\Controller\EsimerkitController::lihapiirakka
